server: #Details of server configuration
  name: test_server #Friendly name that the server will attach to payloads
  ip: 127.0.0.1 #IP address of the server
  port: 5000 #Port of the server

auth:
  ip-list: #List of IPs that are authorized to connect to the server
    - 127.0.0.1
  api-keys: #List of API keys that are authorized to connect to the server
    - I am your Father

epics: #Details of EPICS configuration
  state: VIRTUAL #State of the EPICS server (VIRTUAL or PHYSICAL)
  set-env: true #Set the environment variables for the EPICS server
  addr-list: 192.168.83.246 #EPICS_CA_ADDR_LIST
  auto-addr: 'NO' #EPICS_CA_AUTO_ADDR_LIST
  server-port: '6020' #EPICS_CA_SERVER_PORT
  pv-list: #List of PVs that the server will monitor on start
    - CLA-C2V-DIA-BPM-01:X #PV name